api_specifications/advocate-api-1.0.0.yaml
api_specifications/court-api-1.0.yaml

added Court API and fixed errors in Advocate API with regards incorrect reference paths to the required schema objects

Court API and fixed errors in Advocate API

---

mobile/pucardpg/android/app/src/main/AndroidManifest.xml
mobile/pucardpg/lib/app/presentation/features/address_screen/address_screen.dart
mobile/pucardpg/lib/app/presentation/features/advocate-registration-screen/advocate_registration_screen.dart
mobile/pucardpg/lib/app/presentation/features/id-otp-screen/id_otp_screen.dart
mobile/pucardpg/lib/app/presentation/features/id-verification-screen/id_verification_screen.dart
mobile/pucardpg/lib/app/presentation/features/mobile-number-screen/mobile_number_screen.dart
mobile/pucardpg/lib/app/presentation/features/name-details-screen/name_details_screen.dart
mobile/pucardpg/lib/app/presentation/features/otp-screen/otp_screen.dart
mobile/pucardpg/lib/app/presentation/features/success-screen/success_screen.dart
mobile/pucardpg/lib/app/presentation/features/t&c-screen/terms_and_conditions_screen.dart
mobile/pucardpg/lib/app/presentation/features/user-type-screen/user_type_screen.dart
mobile/pucardpg/lib/main.dart
mobile/pucardpg/pubspec.yaml

Mobile address with map, pdf selection and display

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomDetailsCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/index.js

Case Type modal completed

---

backend/case/src/main/java/org/pucar/dristi/config/Configuration.java
backend/case/src/main/java/org/pucar/dristi/enrichment/WitnessRegistrationEnrichment.java
backend/case/src/main/java/org/pucar/dristi/service/WitnessService.java
backend/case/src/main/java/org/pucar/dristi/validators/WitnessRegistrationValidator.java
backend/case/src/main/java/org/pucar/dristi/web/controllers/CaseApiController.java
backend/case/src/main/resources/application.properties
backend/case/witness-persister.yml

witness update api

---

api_specifications/advocate-api-0.1.0.yaml
api_specifications/case-api-0.1.0.yaml
api_specifications/case-management-api-0.1.0.yaml

Significant changes to Advocate API. Extended search to support multiple different APIS for search, to make it implementation friendly. 
Some changes to CMS API - update the CaseSummary object to pick specific fields from the Case

modified Advocate and Case Mgmt Service APIs. 

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/index.js

1. Basic Config added for signature page
2. Remaing tasks - Address component, info component, multiple doc wrapper component, Functionality of editing the details, styling

Signature page config done

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateDetailComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectId.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectOtp.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/EnterAdhaar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/Response.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/UploadIdType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/config.js

D15, D16, D27, D28,D50, D51, D59,D73,D77, D78 fixes Bug fixes Round 2

 D15, D16, D27, D28,D50, D51, D59,D73,D77, D78 fixes

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomRadioCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RadioButton.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectId.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectMobileNumber.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectOtp.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js

complete till select id
after this merging, bug D29 - D47 (except D44) will got fixed

User registration UI fix

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/inbox.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/Home.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

naya mitra home screen and view cases ui fixed

naya mitra home screen and view cases ui fixed

---

backend/advocate/src/main/java/org/pucar/dristi/enrichment/AdvocateClerkRegistrationEnrichment.java
backend/advocate/src/main/java/org/pucar/dristi/repository/AdvocateRepository.java
backend/advocate/src/main/java/org/pucar/dristi/repository/querybuilder/AdvocateClerkQueryBuilder.java
backend/advocate/src/main/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilder.java
backend/advocate/src/test/java/org/pucar/dristi/repository/querybuilder/AdvocateClerkQueryBuilderTest.java
backend/advocate/src/test/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilderTest.java

new changes from dev_backend_advocate

Dev backend advocate bis improve coverage

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/inbox.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js

view application bug fixed and select name error msg fixed.
bugs D133, 126,117,114,123,128

view application bug fixed and select name error msg fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/ApplicationAwaitingPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/TakeUserToRegistration.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectName.js

Qa bug fixes

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectMobileNumber.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/UploadIdType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js

logout dropdown position change, otp bug fix, others

logout dropdown position change, otp bug fix, others

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customDragDrop.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadFile.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/UploadIdType.js

Card expand bug fix and small e filling changes

Card expand bug fix and small e filling changes

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectId.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectOtp.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js

new bugs- D024, D015, D017(new deployed), D013, D019(known bug sheet) , Add back buton on enter mobile number page for new user

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/toast.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectId.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/EnterAdhaar.js

toast and localisation fix

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdhaarInput.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectId.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectOtp.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js

User registration mobile and edit profile bug

User registration mobile

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customDragDrop.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customErrorTooltip.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customNote.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customTextArea.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectBulkInputs.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadFiles.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/prayerAndSwornConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/respondentConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/witnessConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js

e filing ui fix except singature and modal

e filing ui fix

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customDragDrop.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/EsignAdharModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SignatureCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/prayerAndSwornConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/signatureconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

signature page with modlal ui fixed and add document with file name fixed

signature page add prayer and sworn

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/caseWorkflow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ErrorsAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

1. Marking prev errors in blue color
2. Enabling only the fields where Scrutiny office has added errors when it comes to scrutiny nth time
3. Showing total page wise errors in Total Errors accordion to litigent

SCrutiny showing error accordion and marking previous errors in blue colour

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Judge/JudgeScreen.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersHome.js

redirect and button added

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

Following bug fixed:
1) redirection to home page when click on logo #578 
2) we were able continure if additional details in prayer sworn is empty #539

Bug fix e filing 539

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/AddAttendees.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/DisplayAttendees.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/MarkAttendance.js

added view attendees

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/DataContext.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js

Added pre hearing modal

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js

Join case minor bug fixes

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js

Join case api and some minor bug

Join case api and some minor bug

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

replacing advocate with new advocate
when new advocate take over the primary advocate then we wanted to replace that representative with new advocate details. if we replace then old advocate shouldn't be  the part of the case.

replacing advocate with new

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCaseInfoDiv.js

court complex name added, changed fullName formate of select party dropdown and customCaseInfo td width fix

court complex name added and customCaseInfo td width fix

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/submissions/submissionApplication.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js

review submission modal ui fix and docviewer integrated

review submission modal ui fix and docviewer integrated

---

docs/Case/schemas/case-nia.json

updated case-nia schema to add required fields

updated case-nia schema to add required fields

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

minor bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

double enter enable bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

disable proceed button bug

---

backend/casemanagement/src/main/resources/application.properties

added redis port in properties file

properties file updated

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

E filing evidence upload

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js

source id changed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js

added case admit loader and removed Pre Trial from stage

added case admit loader and removed Pre Trial from stage

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/homehearing.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js

Bench clerk home screen and bug fixes

Bench clerk home screen

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

esign and case approver bug fixed

Bench role fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/upcomingHearing.scss
frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/taskcomponent.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js

case stage and Hearing api bug fixed and fixed following bugs:
1. When there are hearings scheduled for the day Hearing card (Component) is not showing for Litigant
2. When the hearings scheduled for the day Hearings are not showing in list of hearing for Advocate
3. View Hearing need to replace with View Hearings
4. By default Filters are selected

case stage and Hearing api bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js

task filter bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

remove debounce from case search join case

remove debounce from case search join case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

added case search on enter button

added case search on enter button

---

api_specifications/case-api-0.1.0.yaml
api_specifications/order-api-0.1.0.yaml
docs/task/workflow/workflowConfig-bail.json
docs/task/workflow/workflowConfig-summon.json
docs/task/workflow/workflowConfig-warrant.json

1. added outcome field to case API to store the final case outcome 
2. updated summons, bail and warrants workflows to handle the re-issue, and un-delivered status

task workflow and case api update

---

backend/casemanagement/src/main/java/org/pucar/dristi/config/Configuration.java
backend/casemanagement/src/main/java/org/pucar/dristi/service/ServiceUrlEntityRequestService.java
backend/casemanagement/src/main/java/org/pucar/dristi/service/ServiceUrlMapperVCService.java
backend/casemanagement/src/main/java/org/pucar/dristi/util/MdmsV2Util.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/CredentialRequest.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/Mdms.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/MdmsCriteriaReqV2.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/MdmsCriteriaV2.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/MdmsResponseV2.java
backend/casemanagement/src/main/resources/application.properties
backend/casemanagement/src/test/java/org/pucar/dristi/service/ServiceUrlMapperVCServiceTest.java
backend/casemanagement/src/test/java/org/pucar/dristi/util/MdmsV2UtilTest.java

Modified generate VC validation in the case management service.

Case management vc

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetStatuteSection.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js

formate date and fixed no hearing box, added mdms hook for getting case statute and sections

formate date and fixed no hearing box

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/Accordian.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/Urls.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js

creation of task_bar_in_calander

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js

Reverts pucardotorg/dristi#1156

Revert "bug_fixes"

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/AddAttendees.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/DisplayAttendees.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/MarkAttendance.js

changed the payload for update hearing update_transcript_additional_attendees API

 changed the payload for update hearing update_transcript_additional_attendees API and added attendee type in display attendee component

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

Summon payment modal intregation and ui fixed

Summon payment modal intregation

---

backend/application/postman/Application.postman_collection.json
backend/evidence/postman/Evidence.postman_collection.json

added add comment api in postman

updated postman

---

backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
backend/application/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
backend/application/src/main/java/org/pucar/dristi/util/FileStoreUtil.java
backend/application/src/main/java/org/pucar/dristi/validator/ApplicationValidator.java
backend/application/src/main/resources/application.properties
backend/application/src/test/java/org/pucar/dristi/util/FileStoreUtilTest.java
backend/application/src/test/java/org/pucar/dristi/validator/ApplicationValidatorTest.java
backend/hearing/src/main/java/org/pucar/dristi/config/Configuration.java
backend/hearing/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/hearing/src/main/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichment.java
backend/hearing/src/main/java/org/pucar/dristi/util/FileStoreUtil.java
backend/hearing/src/main/java/org/pucar/dristi/validator/HearingRegistrationValidator.java
backend/hearing/src/main/resources/application.properties
backend/hearing/src/test/java/org/pucar/dristi/util/FileStoreUtilTest.java
backend/hearing/src/test/java/org/pucar/dristi/validator/HearingRegistrationValidatorTest.java
backend/order/src/main/java/org/pucar/dristi/config/Configuration.java
backend/order/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/order/src/main/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichment.java
backend/order/src/main/java/org/pucar/dristi/util/FileStoreUtil.java
backend/order/src/main/java/org/pucar/dristi/validators/OrderRegistrationValidator.java
backend/order/src/test/java/org/pucar/dristi/util/FileStoreUtilTest.java
backend/order/src/test/java/org/pucar/dristi/validators/OrderRegistrationValidatorTest.java

enriching document id on update

enrich doc id on update

---

docs/asyncsubmission/workflow/ordersubmission-workflowConfig 1.json
docs/asyncsubmission/workflow/ordersubmissionwithresponse-workflowConfig 1.json
docs/order/workflow/workflowConfigJudgement.json
docs/task/schemas/task-warrant.json

1. Updated warrant schema to include the following 
`  "warrantDetails":
{
"warrantId": {
"type" : "string",
"description": "alphanumeric string representing the warrant ID"
},
"warrantType": {
"type" : "string",
"pattern": "^[a-zA-Z]{1,32}$",
"description": "type like arrest, etc. string having a max of 32 alphabets. no numbers"
},
"isBailable": {
"type": "boolean"
},
"sureties": {
"type": "string",
"enum" : ["one", "two"]
},
"suretyAmount": {
"type": "integer",
"minimum": 0
}
},`
2. Updated Order based submission workflows to remove Payment and Delay steps from it.

Warrant Schema and Submission Workflows updated

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateDetailComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js

dubplicate bar number fix, file preview in selectCustomDragDrop

---

docs/Advocate/worfkow/advocateclerkregistration-workflowConfig.json
docs/Advocate/worfkow/userregistration-workflowConfig.json
docs/Evidence/workflow/artifact-workflowConfig.json
docs/application/workflow/application-workflowConfig.json
docs/asyncsubmission/workflow/ordersubmission-workflowConfig.json
docs/asyncsubmission/workflow/ordersubmissionwithresponse-workflowConfig.json
docs/asyncsubmission/workflow/voluntarysubmission-workflowConfig.json
docs/hearing/workflow/hearing-workflowConfig.json
docs/order/workflow/order-workflowConfig.json
docs/task/workflow/task-workflowConfig.json
docs/task/workflow/workflowConfig-bail.json

workflow consistency in naming actions and states and updated SLA and also added for auto escalation

Workflow updates

---

api_specifications/case-api-0.1.0.yaml
api_specifications/hearing-api-0.1.0.yaml

added api to verify access code for a case

added api to verify access code for a case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/delayApplicationConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

#1513 and #1222 comment changes

e-filing config changes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomNote.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Judgement order changes
